application: save-my-receipt
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest

handlers:
- url: /.*
  script: savemyreceipt.application